// Light.
export const ACTIVATED_OPACITY_HOVER_LIGHT = 0.18;
export const ACTIVATED_OPACITY_FOCUS_LIGHT = 0.23;
export const ACTIVATED_OPACITY_ACTIVE_LIGHT = 0.30;

// Dark.
export const ACTIVATED_OPACITY_HOVER_DARK = 0.35;
export const ACTIVATED_OPACITY_FOCUS_DARK = 0.45;
export const ACTIVATED_OPACITY_ACTIVE_DARK = 0.55;
